version: "3.4"
services:
  app:
    build: 
      context: docker/
      args: 
        - FIX_UID=${FIX_UID}
        - FIX_GID=${FIX_GID}
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app/
    volumes:
      - "../app:/usr/src/app:cached"
    environment:
      - DNSDOCK_ALIAS=${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - VIRTUAL_HOST=${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - VIRTUAL_PORT=8000
